name: CI
on:
 issue_comment:
   types: [created, edited]
 issues:
   types: [opened, edited]

jobs:
  snippet-runner:
    timeout-minutes: 2
    runs-on: "ubuntu-latest"
    steps:
    - uses: lwronski/scala-snippet-checker@0ba3ca17c4d599be2e5902ecebbf4170d0a1195d