name: CI
on:
  push:
    branches:
    - main

jobs:
   scala-cli:
      runs-on: ${{ matrix.OS }}
      strategy:
        fail-fast: false
        matrix:
          OS: ["ubuntu-latest", "macos-latest", "windows-latest"]
      timeout-minutes: 120
      steps:
       - uses: actions/checkout@v2
       - uses: coursier/cache-action@v6
       - uses: lwronski/scala-cli-setup-action@main
         with:
          apps: scala-cli
       - run: scala-cli
       - run: echo 'println("Hello")' | scala-cli -
       - run: echo 'println("Hello")' | scala-cli -
